apiVersion: v1
kind: Service
metadata:
  name: infrasnap-service
  namespace: infrasnap
spec:
  selector:
    app: infrasnap-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
